### ISSUE TITLE
三項演算子について

### ISSUE THREAD

**Issue by Sakurai00** [rutti-bep/genshin-notification-bot#8]
三項演算子使うのはやばいでしょｗｗ

[](https://tenor.com/view/%e0%b8%94%e0%b8%b6%e0%b8%87%e0%b9%81%e0%b8%81%e0%b9%89%e0%b8%a1-%e0%b9%81%e0%b8%a1%e0%b8%a7-%e0%b8%ab%e0%b8%a1%e0%b8%b1%e0%b9%88%e0%b8%99%e0%b9%80%e0%b8%82%e0%b8%b5%e0%b9%89%e0%b8%a2%e0%b8%a7-%e0%b9%84%e0%b8%ad%e0%b9%89%e0%b8%95%e0%b9%89%e0%b8%b2%e0%b8%a7-%e0%b8%9a%e0%b8%b5%e0%b8%9a%e0%b9%81%e0%b8%81%e0%b9%89%e0%b8%a1-gif-19568157)

https://github.com/rutti-bep/genshin-notification-bot/blob/a4b62794f5990466d9bc3835b2b09642835a3a82/genshinNotificationBot.py#L13-L17

**Comment by rutti-bep** [comment]
なおして ❤️
